name: Generate Anime List
on:
  push:
  schedule:
    - cron: "0/180 * * * *"

jobs:
  build:
    name: Run

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Generate (GogoAnime)
      run: |
        python ./gogoanime/generate.py

    - name: Generate (AnimePahe)
      run: |
        python ./animepahe/generate.py

    - name: Generate (Anilist)
      run: |
        python ./anilist/generate.py

    - name: Generate (MangaDex)
      run: |
        python ./mangadex/generate.py
        
    - name: Generate (Mangakakalot)
      run: |
        python ./mangakakalot/generate.py

    - name: Generate (AsuraScans)
      run: |
        python ./asurascans/generate.py

    - name: Supabase (Gogoanime)
      env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run:  |
        python ./gogoanime/supabase_utils.py
        
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # Optional but recommended
        # Defaults to "Apply automatic changes"
        commit_message: Apply automatic changes

        file_pattern: |
            ./*.json
            ./*.csv

        # Optional local file path to the repository
        # Defaults to the root of the repository
        repository: .

        # Optional: Skip internal call to `git fetch`
        skip_fetch: true
