name: Generate Anime List Cron Job

on:
  push:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Gogoanime (Popular)
        run: node ./gogoanime/popular.js
      - name: Gogoanime (Trending)
        run: node ./gogoanime/trending.js

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
        # Optional but recommended
        # Defaults to "Apply automatic changes"
          commit_message: Apply automatic changes

          file_pattern: ./*.json

        # Optional local file path to the repository
        # Defaults to the root of the repository
          repository: .

        # Optional: Skip internal call to `git fetch`
          skip_fetch: true
